### PR TITLE
Fixes #72

### LINKED ISSUE #72: If Puller - Docs fail to build / deploy
Mat hit this - just needs a try / catch style statement.

### PR DESCRIPTION
**Pull request by gauntface**
Fixes #72 

Pullr fails if two factor auth is required to sign in to github.

cc @jeffposnick @addyosmani @wibblymat @surma

### CODE REVIEW

File: project/perform-release.sh [hunk 1]
```diff
@@ -119,7 +119,13 @@ git push origin -f $currentBranch:release-pr
...
 git reset --hard origin/$currentBranch
 
-./node_modules/pullr/bin/pullr.js --new --from release-pr --into master --title 'Auto-generated PR to update the version number' --description 'Please review this change and ensure that package.json is the ONLY file changed AND that the version matches the latest tagged release.'
+{
+  ./node_modules/pullr/bin/pullr.js --new --from release-pr --into master --title 'Auto-generated PR to update the version number' --description 'Please review this change and ensure that package.json is the ONLY file changed AND that the version matches the latest tagged release.'
+} || {
+  echo ""
+  echo "ERROR: Unable to auto-generate the Pull Request from release-pr into master. Please do so manually."
+  echo ""
+}
```
Comment (surma) [inline project/perform-release.sh]: Sorry if I am being dumb here, but are you sure about `{` and `}`? I always thought shell scripts used `(` and `)` while curly braces are for variable expansion.

Comment (surma) [inline project/perform-release.sh]: Just saw the comment for the curly braces in the other PR. TIL!

**Comment by surma** [comment]
LGTM
